modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/TropheusJ/stonecutter-groups/issues"
license = "MIT"

[[mods]]
modId = "stonecutter_groups_test"
version = "1.0.0"
displayName = "Stonecutter Groups Test"
authors = "Tropheus Jay"
description = '''
Provides a new group-based method of creating stonecutter recipes.
'''

[[dependencies.stonecutter_groups_test]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.stonecutter_groups_test]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"
